const drugNames: string[] = [
    'Aspirin',
    'Paracetamol',
    'Ibuprofen',
    'Lisinopril',
    'Simvastatin',
    'Metformin',
    'Zinc oxide',
    'Zinc sulfate',
    'Zolendronic acid',
    'Vinblastine',
    'Vincristine',
    'Vinorelbine',
    'Vitamin B complex',
    'Voriconazole',
    'Warfarin',
    'Water for injection',
    'Xylometazoline',
    'Yellow fever vaccine',
    'Zidovudine',
    'Abacavir',
    'Acetazolamide',
    'Acetylcysteine',
    'Acetylsalicylic acid',
    'Aciclovir',
    'Adenosine',
    'Albendazole',
    'Alendronic acid',
    'Alfacalcidol',
    'Allopurinol',
    'Aluminium hydroxide',
    'Amikacin',
    'Aminoacid',
    'Aminophylline',
    'Amiodarone',
    'Amitriptyline',
    'Amoxicillin',
    'Amphotericin B',
    'Ampicillin',
    'Anastrazole',
    'Anti D immunoglobulin (human)',
    'Antirabies equine serum',
    'Antitetanus immunoglobulin',
    'Antivenom serum',
    'Aqueous cream',
    'Artemether with Lumefantrine',
    'Ascorbic acid',
    'Asparaginase',
    'Atenolol',
    'Atorvastatin',
    'Atracurium',
    'Atropine',
    'Azathioprine',
    'Azithromycin',
    'Baclofen',
    'Balanced salt',
    'Barium sulfate',
    'BCG vaccine',
    'Beclometasone',
    'Benzathine benzylpenicillin',
    'Benztropin mesylate',
    'Benzyl benzoate',
    'Benzyl peroxide',
    'Benzylpenicillin',
    'Beractant',
    'Betahistine',
    'Betametasone',
    'Betaxalol',
    'Bicalutamide',
    'Bisacodyl',
    'Bleomycin sulfate',
    'Bupivacaine',
    'Calamine',
    'Calcitriol',
    'Calcium carbonate/ lactate',
    'Calcium folinate',
    'Calcium gluconate',
    'Capecitabine',
    'Captopril',
    'Carbamazepine',
    'Carbimazole',
    'Carboplatin',
    'Carvedilol',
    'Cefalexin',
    'Cefipime',
    'Cefotaxime',
    'Ceftazidime',
    'Ceftriaxone',
    'Cefuroxime',
    'Cetirizine',
    'Cetrimide',
    'Charcoal, activated',
    'Chloral Hydrate',
    'Chlorambucil',
    'Chloramphenicol',
    'Chlordiazepoxide',
    'Chlorhexidine',
    'Chlorine base compound',
    'Chloroquine',
    'Chlorphenamine',
    'Chlorpromazine',
    'Ciclosporin',
    'Cinnarizine',
    'Ciprofloxacin',
    'Cisplatin',
    'Clarithromycin',
    'Clindamycin',
    'Clofazimine',
    'Clomifene',
    'Clomipramine',
    'Clonazepam',
    'Clopidogrel',
    'Clotrimazole',
    'Cloxacillin',
    'Clozapine',
    'Coal tar',
    'Coconut oil compound',
    'Codeine phosphate',
    'Cold compounds to prepare radio pharmaceuticals',
    'Co‐magaldrox',
    'Compound Sodium lactate',
    'Condoms',
    'Conjugated estrogens',
    'Copper containing device',
    'Cyanocobalamin',
    'Cyclopentolate',
    'Cyclophosphamide',
    'Cycloserine',
    'Cyproheptadine',
    'Cytarabine',
    'Dacarbazine',
    'Dactinomycin',
    'Deferiprone',
    'Deferoxamine',
    'Desmopressin',
    'Dexamethasone',
    'Dextran 70',
    'Diaphragms (male/female)',
    'Diazepam',
    'Diclofenac sodium',
    'Didanosine',
    'Diethylcarbamazine citrate',
    'Digoxin',
    'Diltiazem',
    'Dimercaprol',
    'Dinoprostone',
    'Diphtheria and tetanus (Adult) (aDT) vaccine',
    'Diphtheria and tetanus (DT) vaccine',
    'Diphtheria, Pertussis and Tetanus (DPT) vaccine',
    'Dithranol',
    'DL‐methionine',
    'Dobutamine',
    'Docetaxel',
    'Domperidone',
    'Dopamine',
    'Dopamine agonist',
    'Dorzolamide',
    'Doxorubicin',
    'Doxycycline',
    'Duloxetine',
    'Edrophonium',
    'Efavirenz',
    'Emulsifying ointment',
    'Enalapril',
    'Enoxaparin',
    'Ephedrine',
    'Epirubicin',
    'Ergocalciferol',
    'Ergometrine',
    'Erythromycin',
    'Erythropoetin',
    'Esmolol',
    'Ethambutol',
    'Ethanol',
    'Ethinylestradiol',
    'Ethionamide',
    'Ethosuximide',
    'Etonogestrel',
    'Etoposide',
    'Exemestane',
    'Factor IX complex concentrate',
    'Factor VII concentrate',
    'Factor VIII concentrate',
    'Famotidine',
    'Fat Emulsion',
    'Fentanyl',
    'Fentanyl citrate',
    'Ferrous salt',
    'Filgastrim',
    'Finasteride',
    'Flucinolone/Clobetasol',
    'Fluconazole',
    'Fludrocortisone',
    'Flumazenil',
    'Flunarazine',
    'Fluorescein',
    'Fluorometholone',
    'Fluorouracil',
    'Fluoxetine',
    'Fluphenazine',
    'Flutamide',
    'Folic acid',
    'Follitropin Alfa/beta',
    'Framycetin',
    'Fuller’s earth',
    'Furazolidone',
    'Furosemide',
    'Fusidic Acid',
    'Gadolinium',
    'Gemcitabine',
    'Gemfibrozil',
    'Gentamicin',
    'Glibenclamide',
    'Glucagon',
    'Glucose',
    'Glucose with sodium chloride',
    'Glutetaldehyde',
    'Glyceryl trinitrate',
    'Gosereline',
    'Griseofulvin',
    'Haemophilus influenzae type B (Hib) conjugate vaccine',
    'Haloperidol',
    'Halothane',
    'Heparin',
    'Hepatitis A vaccine',
    'Hepatitis A vaccine(adult)',
    'Hepatitis A vaccine (paediatric)',
    'Hepatitis B vaccine',
    'Homotropine',
    'Human Growth Hormone',
    'Human Menopausal Gonadotrophin (Follicle stimulating hormone + Lutenising hormone)',
    'Hydralazine',
    'Hydrochlorothiazide',
    'Hydrocortisone',
    'Hydrogen peroxide',
    'Hydroxocobalamin',
    'Hydroxychloroquine',
    'Hydroxyurea',
    'Hyoscine butylbromide',
    'Ibandronic Acid',
    'Ibuprofen',
    'Ichthammol',
    'Ifosfomide with Mesna',
    'Imatinib',
    'Imipramine',
    'Indinavir',
    'Insulin (soluble)',
    'Interferon',
    'Intermediate‐acting insulin',
    'Intraperitoneal dialysis',
    'Iohexol',
    'Ipratropium Bromide',
    'Irinotecan',
    'Isoflurane',
    'Isoniazid',
    'Isoprenaline',
    'Isosorbide dinitrate',
    'Isosorbide mononitrate',
    'Isotretinoin',
    'Itraconazole',
    'Japanese encephalitis vaccine',
    'Kanamycin',
    'Ketamine',
    'Ketorolac',
    'Labetalol',
    'Lactulose',
    'Lamivudine',
    'Lamotrigine',
    'Lead',
    'Leflunomide',
    'Letrozole',
    'Levofloxacin',
    'Levonorgestrel IUD',
    'Levonorgestrel',
    'Moxifloxacin',
    'Mycophenolate',
    'Levothyroxine',
    'Nalidixic acid',
    'Lidocaine',
    'Naloxone',
    'Lidocaine',
    'Natamycin',
    'Neostigmine',
    'Netilmicin sulfate',
    'Nevirapine',
    'Nifedipine',
    'Liquid paraffin',
    'Nitrofurnatoin',
    'Lithium carbonate',
    'Nitrous oxide',
    'Lomustine',
    'Noradrenaline',
    'Loperamide',
    'Norethisterone',
    'Norfloxacin',
    'Lorazepam',
    'Normal immunoglobulin (human)',
    'Losartan',
    'Nystatin',
    'Magenta paint',
    'Octreotide',
    'Magnesium sulfate',
    'Ofloxacin',
    'Malathion',
    'Olanzapine',
    'Mannitol',
    'Omeprazole',
    'Measles Rubella vaccine',
    'Ondansetron',
    'Measles vaccine',
    'Oral rehydration salts',
    'Mebendazole',
    'Oxaloplatin',
    'Medroxyprogesterone',
    'Oxybutinin',
    'Megestrol acetate',
    'Oxygen',
    'Melphalan',
    'Oxymetazoline',
    'Meningococcal meningitis',
    'Oxytocin',
    'Mercaptopurine',
    'Paclitaxel',
    'Meropenem',
    'Pamidronate',
    'Metformin',
    'Pancreatin',
    'Methadone',
    'Pancuronium',
    'Methimazole',
    'Pantaprazole',
    'Methionine',
    'Methotrexate',
];
export default drugNames;

